[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tensor_toolbox"
version = "0.1.0"
description = "A python  toolbox for the tensor linear algebra under the t-product"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "Jeremie Mabiala", email = "jnlandu@gmail.com" },
]
dependencies = [
  "numpy",
  "torch",
]

keywords = [
  "tensor",
  "t-product",
  "tensor linear algebra",
]

classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering :: Mathematics",
]

[project.urls]
Repository = "https://github.com/jnlandu/tensor-tensor-toolbox-in-python"
Homepage = "https://jnlandu.github.io/"

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["tensor_toolbox*"]

[tool.setuptools.exclude-package-data]
"*" = ["__pycache__", "*.pyc"]
